environment:
  nodejs_version: '12'

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn --frozen-lockfile

test_script:
  - git --version
  - node --version
  - yarn --version
  - cd packages\vite && yarn build

cache:
  - node_modules -> yarn.lock

build: off
