version: 2

defaults: &defaults
  docker:
    - image: vuejs/ci

step_restore_cache: &restore_cache
  restore_cache:
    keys:
    - v1-dependencies-{{ checksum "yarn.lock" }}-1
    - v1-dependencies-

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: yarn --frozen-lockfile

step_save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
      - ~/.cache/yarn
    key: v1-dependencies-{{ checksum "yarn.lock" }}-1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: rm -rf ~/project/node_modules/esbuild/.install
      - *install_deps
      - *save_cache
      - run: yarn build
      - run: yarn test

workflows:
  version: 2
  ci:
    jobs:
      - test
