name: Lock Closed Issues

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write

jobs:
  action:
    if: github.repository == 'vitejs/vite'
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@3809910bc12872edc9b8132f122069ac16cd16ee # v3
        with:
          actions: "lock-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          #body: |
          #  This issue has been locked since it has been closed for more than 14 days.
          #
          #  If you have found a concrete bug or regression related to it, please open a new [bug report](https://github.com/vitejs/vite/issues/new/choose) with a reproduction against the latest Vite version. If you have any other comments you should join the chat at [Vite Land](https://chat.vite.dev) or create a new [discussion](https://github.com/vitejs/vite/discussions).
          issue-state: closed
          inactive-day: 14
